### ISSUE TITLE
Add template for executing SPARQL queries via ROBOT

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-starter-kit#20]
Prompted by https://github.com/EnvironmentOntology/envo/issues/494

Proposed layout:

```
src/
   sparql/
       query1.sparql
       ...
   ontology/
        reports/
             query1-results.tsv
             ...
reports/
    query1-results.tsv  <-- copied from target during release
```

Should we make an attempt to standardize the sparql queries or can people modify them?

**Comment by jamesaoverton** [comment]
If they're standardized, then I don't think that they should live in individual repositories, because people won't update them. I've been thinking of a central repository and a ROBOT command to fetch and run them.

**Comment by cmungall** [comment]
That sounds good. I'll hold off on this ticket til we see what this looks like. Eric can also help with the central repo thing if you want to spec it out.

**Comment by pbuttigieg** [comment]
@jamesaoverton good point - ENVO needed a bunch of SPARQL outputs due to user requests, but not all ontologies will have the same need. 

That being said, I'd anticipate that many SPARQL queries would be quite standard (e.g. flat TSVs containing subsets of terms) so a central repo would serve as a good library to which interested users can submit their own creations.

**Comment by jamesaoverton** [comment]
Yes. Having local, project-specific queries is a good idea, and this layout is fine.

We also want to design some OBO-standard queries, to validate some of our shared best practises. I was thinking of the latter in my comment above. I would be good to start on this and work out some of the details. Unfortunately, I can't promise I'll have time soon, so don't wait for me.

**Comment by cmungall** [comment]
Can you assign @dougli1sqrd to a robot team, he can work on it

**Comment by cmungall** [comment]
Done in #24
